Update build-release.yml

diff --git a/.github/workflows/build-release.yml b/.github/workflows/build-release.yml
--- a/.github/workflows/build-release.yml
+++ b/.github/workflows/build-release.yml
@@ -1,12 +1,15 @@
 name: build-release
+
 on:
   push:
     branches:
       - main
       - master
   workflow_dispatch:
+
 permissions:
   contents: write
+
 jobs:
   build-android:
     runs-on: ubuntu-latest
@@ -22,12 +25,40 @@ jobs:
         with:
           distribution: temurin
           java-version: "17"
+      - run: |
+          if [ -z "${ANDROID_KEYSTORE_BASE64}" ]; then
+            echo "ANDROID_KEYSTORE_BASE64 is missing"
+            exit 1
+          fi
+          echo "$ANDROID_KEYSTORE_BASE64" | base64 -d > android/app/release.keystore
+        env:
+          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
       - run: flutter pub get
-      - run: flutter build apk --debug --split-per-abi
-
-      # 上传产物到当前Actions任务的Artifacts（直接在这里下载，不用Release）
-      - name: Upload debug apk artifacts
-        uses: actions/upload-artifact@v4
+      - run: flutter build apk --release --split-per-abi
+        env:
+          SIGNING_STORE_FILE: release.keystore
+          SIGNING_STORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
+          SIGNING_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
+          SIGNING_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
+      - run: |
+          FULL_VERSION=$(grep '^version:' pubspec.yaml | awk '{print $2}')
+          VERSION=${FULL_VERSION%%+*}
+          echo "VERSION=$VERSION" >> $GITHUB_ENV
+      - run: |
+          git log -1 --pretty=format:"- %s%n%b" > release_notes.txt
+          if [ ! -s release_notes.txt ]; then
+            echo "- ${GITHUB_SHA}" > release_notes.txt
+          fi
+      - run: |
+          mv build/app/outputs/flutter-apk/app-arm64-v8a-release.apk nagomusic-v${VERSION}-arm64-v8a.apk
+          mv build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk nagomusic-v${VERSION}-armeabi-v7a.apk
+          mv build/app/outputs/flutter-apk/app-x86_64-release.apk nagomusic-v${VERSION}-x86_64.apk
+      - uses: softprops/action-gh-release@v2
         with:
-          name: nagomusic-debug-apk
-          path: build/app/outputs/flutter-apk/*.apk
+          tag_name: v${{ env.VERSION }}
+          name: v${{ env.VERSION }}
+          body_path: release_notes.txt
+          files: |
+            nagomusic-v${{ env.VERSION }}-arm64-v8a.apk
+            nagomusic-v${{ env.VERSION }}-armeabi-v7a.apk
+            nagomusic-v${{ env.VERSION }}-x86_64.apk
